[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[services]]
[services.web]
startCommand = "npm start"
healthcheckPath = "/health"

[env]
NODE_ENV = "production"
LOG_LEVEL = "info" 